### ISSUE TITLE
depends_on uses wrong name

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/green-metrics-tool#871] opened 2024-08-21 18:43 UTC
This will fail:
```
services:
  nginx:
    image: nginx:latest
    container_name: nginx_https

  curl:
    build:
      context: .
      dockerfile: curl.Dockerfile
    container_name: curl_client
    depends_on:
      - nginx
```

As docker compose wants the key, hence `nginx` but we use `dependent_container_name` so `nginx_https`

https://github.com/green-coding-solutions/green-metrics-tool/blob/81c3ff9fd51f36af68424973d2ee41209864ec67/runner.py#L906

Error can be found here:

https://metrics.green-coding.io/stats.html?id=d6e03f31-0dab-47da-81a5-cede40bcb7a8

**Comment by ArneTR** [comment] 2024-09-08 20:08
This should have been fixed by @davidkopp 

See this PR: https://github.com/green-coding-solutions/green-metrics-tool/pull/860

@ribalba Can you confirm if you have seen the error again since then?

**Comment by ribalba** [comment] 2024-09-09 10:20
Still seems to fail https://metrics.green-coding.io/stats.html?id=ba077a5a-02bd-4de5-9a3e-15fedb1d5bd2

**Comment by davidkopp** [comment] 2024-09-09 10:46
I think the issue is that the machine is using an old GMT version.

The machine with the ID 5 uses the GMT version [e3c...eee](https://github.com/green-coding-berlin/green-metrics-tool/commit/e3c0e6e7628116389b746602a7544c1af7349eee) from Aug 7. My fix was merged with commit [6413439](https://github.com/green-coding-solutions/green-metrics-tool/commit/64134395e83e6e57cf6247a2b0ec11b562d1fa95) on Aug 14.

**Comment by ArneTR** [comment] 2024-09-09 10:55
Yes, agreed.

@ribalba I will make the next update cycle on the machines as soon as #852 and #872 are reviewed by you and merged in

**Comment by ribalba** [comment] 2024-10-14 11:50
@ArneTR both runs don't show any data anymore? This should be fixed by now?

**Closed** 2024-10-14 12:58 UTC
