### ISSUE TITLE
Cluster timing checks

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/green-metrics-tool#790] opened 2024-05-29 14:34 UTC
With the option to introducing waiting times in the usage_scenario file an adversary could not block our cluster by having very long wait times. When a job is run we should check that these times are something reasonable.

**Comment by ArneTR** [comment] 2024-05-29 14:36
Duplicate of: https://github.com/green-coding-solutions/green-metrics-tool/issues/23

**Closed** 2024-05-29 14:36 UTC
